//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace Tabels
{
    using System;
    using System.Collections.Generic;
    [KnownType(typeof(employee))]
    [KnownType(typeof(department))]
    [KnownType(typeof(credential))]
    public partial class credential
    {
        public string user_name { get; set; }
        public string passcode { get; set; }
        public int id { get; set; }
    
        public  employee employee { get; set; }
    }
}
