//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;
namespace Tabels
{
    using System;
    using System.Collections.Generic;
    [KnownType(typeof(employee))]
    [KnownType(typeof(department))]
    [KnownType(typeof(credential))]
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.credentials = new HashSet<credential>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date_of_hiring { get; set; }
        public string sex { get; set; }
        public Nullable<int> department { get; set; }
    
        public  department department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<credential> credentials { get; set; }
    }
}
